version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d

  app:
    build: ./
    container_name: ml-beans
    restart: always
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_NAME=${MYSQL_DATABASE}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
      - APP_DATA_FOLDER=${APP_DATA_FOLDER}
      - GDRIVE_CREDENTIALS_DATA=${GDRIVE_CREDENTIALS_DATA}
    ports:
      - "8088:8088"
    depends_on:
      - db
