base:
  random_state: 42


data_load:
  dataset_prepare: 'data/processed/prepare_beans.csv'


featurize:
  features_path: 'data/processed/featured_beans.csv'
  encoder_path: 'encoder/encoder.joblib'


data_split:
  test_size: 0.2
  trainset_path: 'data/processed/train_beans.csv'
  testset_path: 'data/processed/test_beans.csv'


train:
  model_path: models/model.joblib


evaluate:
  reports_dir: reports
  metrics_file: 'metrics.json'